import type { Metadata } from "next";
import Script from "next/script";
export const config = { amp: true }

// export const config = { amp: true }
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
 {
  return (
    <html lang="en" amp=''> 
      <head>
      <Script src="https://cdn.ampproject.org/v0.js" strategy="lazyOnload" />
      <Script src="https://cdn.ampproject.org/v0/amp-story-1.0.js" strategy="lazyOnload" custom-element="amp-story" />
      <script async custom-element="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"/>
      <Script src="https://cdn.ampproject.org/v0/amp-video-0.1.js" strategy="lazyOnload" custom-element="amp-video" />
      <Script src="https://cdn.ampproject.org/v0/amp-img-0.1.js" strategy="lazyOnload" custom-element="amp-img" />
      </head>
      <body
        >
          {children}
       
      </body>
    </html>
  );
}
