import type { Metadata } from "next";
import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { ApiProvider } from "@/helpers/apiContext"; // Capitalized for standard convention
import Canonical from "@/components/Canonical";
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'
import Script from "next/script";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <Canonical/>
          <Script type="text/javascript" defer async src="https://www.googletagmanager.com/gtag/js?id=G-SQ89MG760K"  id="google_gtagjs-js"></Script>
          <Script
        defer
          id="gtag"
          dangerouslySetInnerHTML={{
            __html: `
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}

gtag("set","linker",{"domains":["www.w3era.com"]});

gtag("js", new Date());

gtag("set", "developer_id.dZTNiMT", true);

gtag("config", "G-SQ89MG760K");
          `,
          }}
        />
        <Script
        defer
          id="gtag"
          dangerouslySetInnerHTML={{
            __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-6BF8XH1GYF');
          `,
          }}
        />
      </head>
      <body
        className={`${inter.variable} `}>
                  <Toaster />
        <ApiProvider> {/* Wrap the provider around children */}
          {children}
        </ApiProvider>
      </body>
    </html>
  );
}
