import type { Metadata } from "next";
import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { ApiProvider } from "@/helpers/apiContext"; // Capitalized for standard convention
import Canonical from "@/components/Canonical";
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <Canonical/>
      </head>
      <body
        className={`${inter.variable} `}>
                  <Toaster />

        <ApiProvider> {/* Wrap the provider around children */}

          {children}
        </ApiProvider>
      </body>
    </html>
  );
}
